import { PERMISSIONS } from '../../../auth/permissions';
import type { HelpArticle, HelpCategory } from '../types';

export const CATEGORY: HelpCategory = {
  id: 'alerts',
  label: 'Alertas e automações',
  description: 'Área "Requer atenção" do painel, central de alertas, notificações no sino e regras de automação.',
  requiredPermission: PERMISSIONS.alerts.view,
};

export const ARTICLES: HelpArticle[] = [
  {
    id: 'alerts-overview',
    categoryId: 'alerts',
    title: 'Como funcionam os alertas',
    summary: 'O sistema confere a frota sozinho, a cada hora, e cria um alerta quando encontra algo que precisa de alguém: manutenção atrasada, consumo fora do padrão, pneu no limite, orçamento estourando, despesa ou documento vencido.',
    whyItMatters: 'Em vez de abrir cada módulo para procurar problemas, você vê em um só lugar o que precisa de atenção, do mais importante para o menos.',
    steps: [
      'Abra "Alertas" no menu (ou o bloco "Alertas prioritários" do painel).',
      'Clique em um alerta para ver o que aconteceu, a base do alerta (os números que o geraram) e a sugestão do sistema.',
      'Use "Abrir o registro" para ir direto ao veículo, pneu, despesa ou documento envolvido.',
      'Clique em "Assumir" para indicar que você está cuidando; depois marque como resolvido.',
    ],
    notes: [
      'Quando a situação se resolve (a manutenção é registrada, a despesa é paga, o pneu é trocado), o alerta é encerrado automaticamente na verificação seguinte.',
      'Se você resolver um alerta e a situação continuar, ele volta como "recorrente" e sobe na lista de prioridade.',
      'Os alertas são calculados por regras fixas a partir dos dados registrados no sistema — nada é estimado. Se faltar dado (por exemplo, poucos abastecimentos com tanque cheio), o alerta simplesmente não é criado.',
    ],
    keywords: ['alerta', 'aviso', 'problema', 'atenção', 'prioridade'],
    relatedArticleIds: ['alerts-attention', 'alerts-statuses', 'alerts-priority', 'alerts-permissions'],
    requiredPermission: PERMISSIONS.alerts.view,
  },
  {
    id: 'alerts-attention',
    categoryId: 'alerts',
    title: 'A área "Requer atenção" do painel',
    summary: 'Primeiro bloco do painel: uma lista curta do que precisa de alguém agora, com a quantidade e um clique para os registros.',
    steps: [
      'Cada linha mostra quantos itens existem e leva para a lista certa, já filtrada.',
      'Os itens críticos aparecem primeiro, depois os de maior quantidade.',
      'Itens com número zero não aparecem — se a lista estiver vazia, não há nada pendente.',
    ],
    notes: [
      'Há dois tipos de linha: grupos de alertas (atualizados a cada verificação automática, a hora aparece no topo) e filas de trabalho em tempo real (abastecimentos e leituras de hodômetro aguardando revisão, solicitações de manutenção aguardando aprovação, ocorrências críticas abertas, motoristas com CNH vencida).',
      'Cada linha só aparece para quem tem permissão de ver aquele assunto.',
    ],
    keywords: ['requer atenção', 'pendências', 'painel', 'o que fazer hoje'],
    relatedArticleIds: ['alerts-overview'],
  },
  {
    id: 'alerts-statuses',
    categoryId: 'alerts',
    title: 'Situações de um alerta',
    summary: 'Novo → Lido → Em andamento → Resolvido ou Descartado. Abrir um alerta já o marca como lido.',
    notes: [
      'Novo: ninguém abriu ainda.',
      'Lido: alguém viu o alerta.',
      'Em andamento: alguém clicou em "Assumir" e está cuidando — o nome aparece no alerta.',
      'Resolvido: a situação foi tratada (por você ou automaticamente, quando deixou de acontecer).',
      'Descartado: você decidiu não tratar. É preciso informar o motivo, e o sistema não volta a avisar sobre a mesma situação pelos próximos 30 dias.',
      'Alertas resolvidos ou descartados não podem ser reabertos; se a situação voltar, um novo alerta é criado.',
    ],
    keywords: ['assumir', 'resolver', 'descartar', 'situação do alerta'],
    relatedArticleIds: ['alerts-overview'],
    requiredPermission: PERMISSIONS.alerts.view,
  },
  {
    id: 'alerts-priority',
    categoryId: 'alerts',
    title: 'Como a prioridade é definida',
    summary: 'A lista de alertas vem ordenada por prioridade: primeiro a gravidade (crítico, atenção, informativo), depois o impacto, a urgência e se o problema já aconteceu antes.',
    example: 'Uma manutenção preventiva de prioridade crítica que passou 2.000 km do previsto aparece antes de uma despesa atrasada há 2 dias.',
    notes: [
      'É uma ordem prática para decidir o que olhar primeiro — não é uma nota científica.',
      'Para não encher a tela, o sistema só cria alerta quando o limite da regra é atingido (por exemplo, consumo pelo menos 15% pior que a média do próprio veículo).',
    ],
    keywords: ['prioridade', 'ordem', 'gravidade', 'crítico'],
    relatedArticleIds: ['alerts-overview', 'automation-rules'],
  },
  {
    id: 'alerts-notifications',
    categoryId: 'alerts',
    title: 'Notificações (o sino)',
    summary: 'O sino no cabeçalho mostra os avisos que as regras de automação mandaram para você. O número vermelho é a quantidade não lida.',
    steps: [
      'Clique no sino para ver as notificações mais recentes.',
      'Clique em uma notificação para abrir o alerta ou o registro.',
      'Use "Marcar todas como lidas" para limpar o contador.',
    ],
    notes: [
      'Nesta versão os avisos são apenas dentro do sistema — não há envio por e-mail, push ou WhatsApp.',
      'Quando uma regra encontra muitos itens de uma vez, você recebe um único aviso resumido em vez de vários.',
      'Notificações nunca mostram valores em R$; abra o alerta para ver os números (se você tiver permissão).',
    ],
    keywords: ['sino', 'notificação', 'aviso', 'não lidas'],
    relatedArticleIds: ['automation-rules'],
    requiredPermission: PERMISSIONS.alerts.view,
  },
  {
    id: 'automation-rules',
    categoryId: 'alerts',
    title: 'Regras de automação',
    summary: 'Uma regra diz QUANDO o sistema deve agir (o que observar e com qual limite) e ENTÃO o que fazer (criar alerta e/ou avisar pessoas). As regras padrão já vêm prontas.',
    steps: [
      'Abra "Configurações" › "Regras de automação".',
      'Clique em uma regra para ajustar o limite (por exemplo, consumo 20% pior em vez de 15%), o período analisado, a gravidade e quem deve ser avisado.',
      'Para ser avisado quando um fato acontecer (checklist reprovado, ocorrência registrada, leitura suspeita…), crie uma "Nova regra" do tipo "Quando um fato acontecer".',
      'Use "Verificar agora" para rodar as regras na hora, sem esperar a próxima verificação automática.',
    ],
    example: 'Quando: Custo do veículo acima da média do tipo · Acima da média em 30% · últimos 90 dias\nEntão: criar alerta de atenção e avisar todos que podem ver o alerta',
    notes: [
      'Regras padrão podem ser ajustadas ou desativadas, mas não excluídas.',
      'Desativar uma regra encerra os alertas abertos que ela criou.',
      '"Avisar todos que podem ver o alerta" respeita as permissões: quem não pode ver valores, por exemplo, não recebe aviso de custo.',
      'Regras de "fato" só reagem ao que acontecer depois que a regra foi criada.',
    ],
    keywords: ['automação', 'regra', 'gatilho', 'quando então', 'limite', 'configurar alerta'],
    relatedArticleIds: ['automation-triggers', 'alerts-notifications'],
    requiredPermission: PERMISSIONS.automation.manage,
  },
  {
    id: 'automation-triggers',
    categoryId: 'alerts',
    title: 'O que cada regra padrão observa',
    summary: 'Resumo de como cada alerta automático é calculado.',
    notes: [
      'Manutenção preventiva atrasada / próxima: usa o plano de manutenção do veículo (km, horas e data, com a carência do plano). Mostra quanto falta ou quanto passou.',
      'Consumo fora do padrão: compara o consumo médio do período (tanque cheio a tanque cheio) com a média dos 180 dias anteriores do próprio veículo. Precisa de pelo menos 2 trechos no período e 3 antes.',
      'Custo acima da média do tipo: compara o custo total do veículo no período (combustível, manutenção, pneus e despesas) com a média dos outros veículos ativos do mesmo tipo. Precisa de pelo menos 3 outros veículos com custo. Mostra qual fatia mais puxou a diferença.',
      'Orçamento perto do limite: compara o realizado com o orçado do mês e do ano. Acima de 100% o alerta é crítico.',
      'Pneu com sulco baixo: usa o limite de aviso e o mínimo configurados em Configurações › Pneus.',
      'Despesa em atraso: despesa não paga com vencimento passado há pelo menos o número de dias configurado.',
      'Documento vencido ou vencendo: usa o aviso configurado em cada tipo de documento.',
    ],
    keywords: ['cálculo do alerta', 'como é calculado', 'consumo', 'custo médio', 'orçamento'],
    relatedArticleIds: ['automation-rules', 'alerts-permissions'],
  },
  {
    id: 'alerts-permissions',
    categoryId: 'alerts',
    title: 'Quem vê cada alerta',
    summary: 'Cada alerta só aparece para quem tem permissão de ver aquele tipo de informação no módulo de origem.',
    notes: [
      'Alerta de combustível exige ver combustível; de pneus, ver pneus; de manutenção, ver manutenção.',
      'Alertas com valores em R$ (custo do veículo, orçamento) exigem a permissão de valores financeiros e de custo de combustível, manutenção e pneus — as mesmas que liberam o custo total do veículo.',
      'Alertas de documento de motorista exigem também ver motoristas.',
      '"Assumir, resolver e descartar alertas" e "Configurar regras de automação" são permissões separadas.',
    ],
    keywords: ['permissão', 'quem pode ver', 'acesso'],
    relatedArticleIds: ['alerts-overview'],
  },
];
