import { PERMISSIONS } from '../../../auth/permissions';
import type { HelpArticle, HelpCategory } from '../types';

export const CATEGORY: HelpCategory = {
  id: 'financial',
  label: 'Financeiro',
  description: 'Despesas, categorias, centros de custo, orçamentos, despesas recorrentes, custo por veículo, custo por km, TCO e relatórios financeiros.',
  requiredPermission: PERMISSIONS.finance?.view,
};

export const ARTICLES: HelpArticle[] = [
  {
    id: 'financial-overview',
    categoryId: 'financial',
    title: 'Como funciona a gestão financeira',
    summary: 'O módulo Financeiro reúne, em um só lugar, tudo o que a frota gasta: combustível, manutenção, pneus e qualquer outra despesa (seguro, IPVA, pedágio, multas…) que você registrar manualmente.',
    whyItMatters: 'Sem juntar os gastos de cada módulo, é impossível saber quanto um veículo realmente custa por mês ou por km. O painel Financeiro responde isso automaticamente, sem exigir que você digite de novo o que já foi registrado em outro lugar.',
    steps: [
      'Combustível, manutenção e pneus não precisam ser lançados aqui: o sistema já busca esses valores nos módulos onde foram registrados.',
      'Registre à parte apenas despesas que não têm módulo próprio: seguro, IPVA, licenciamento, pedágio, estacionamento, lavagem, multas, aluguel, financiamento, leasing etc.',
      'Configure centros de custo e categorias de despesa conforme a estrutura da sua empresa.',
      'Acompanhe o painel Financeiro, o ranking de veículos e os relatórios.',
    ],
    notes: [
      'Este módulo é um controle de custos operacionais da frota — não substitui um sistema contábil ou fiscal.',
    ],
    keywords: ['financeiro', 'custos', 'gastos da frota'],
    relatedArticleIds: ['financial-expenses', 'financial-dashboard', 'financial-permissions'],
  },
  {
    id: 'financial-permissions',
    categoryId: 'financial',
    title: 'Permissões do módulo Financeiro',
    summary: 'Ver uma despesa e ver o valor em R$ dela são permissões diferentes. Quem não tem a permissão de valores enxerga a tela normalmente, mas os campos em dinheiro aparecem ocultos.',
    whyItMatters: 'Informação financeira é sensível. O sistema separa "ver que a despesa existe" de "ver quanto ela custou", para que cada papel enxergue só o que precisa.',
    notes: [
      '"Visualizar despesas" mostra categoria, data, veículo, motorista e situação — sem valores.',
      '"Visualizar valores financeiros" é quem libera R$ em toda tela do módulo: despesas, painel, relatórios, custo/km e TCO.',
      'Quem registrou uma despesa sempre vê o valor que digitou, mesmo sem a permissão de valores — para poder conferir o que salvou.',
      'Um painel que mistura combustível, manutenção e pneus só mostra o total completo para quem tem a permissão de valores de todos esses módulos ao mesmo tempo. Faltando uma, o sistema avisa "totais parciais" em vez de mostrar um número errado.',
      'Criar, editar, cancelar despesa, registrar pagamento e configurar categorias/centros de custo/orçamentos/recorrentes são permissões próprias, de quem cuida do financeiro no dia a dia.',
    ],
    keywords: ['permissão', 'quem pode ver valores', 'totais parciais'],
    relatedArticleIds: ['financial-overview'],
  },
  {
    id: 'financial-expenses',
    categoryId: 'financial',
    title: 'Registrar uma despesa',
    summary: 'Em "Financeiro" › "Despesas", clique em "Nova despesa". Escolha a categoria, informe a data e o valor, e associe a um veículo, motorista ou centro de custo quando fizer sentido.',
    example: 'Categoria: Pedágio\nVeículo: ABC-1D23\nData: 05/10/2026\nValor: R$ 48,00\nForma de pagamento: Cartão frota',
    steps: [
      'Escolha a categoria (combustível, manutenção e pneus não aparecem na lista — eles vêm dos próprios módulos).',
      'Preencha a descrição, a data da despesa e o valor.',
      'Informe o fornecedor (um texto livre — não é preciso ter a oficina ou o posto cadastrado) e a forma de pagamento.',
      'Se a despesa tiver vencimento, informe-o — isso é o que faz a situação virar "Atrasado" quando passa da data sem pagamento.',
      'Associe a um veículo e/ou motorista quando a despesa for específica de um deles; deixe em branco para uma despesa da frota como um todo.',
      'Escolha um centro de custo, se sua empresa os usa.',
      'Anexe a nota fiscal, o recibo ou o comprovante.',
      'Salve.',
    ],
    notes: [
      'Uma despesa não é excluída: se foi lançada por engano, é cancelada (com motivo), e continua no histórico.',
      'Se já existir outra despesa igual (mesmo veículo, categoria, valor e data), o sistema avisa "possível duplicidade" — sem bloquear, para você decidir.',
    ],
    keywords: ['lançar despesa', 'cadastrar gasto', 'nova despesa'],
    requiredPermission: PERMISSIONS.finance?.create,
    relatedArticleIds: ['financial-payment-status', 'financial-categories', 'financial-cost-centers', 'financial-edit-cancel'],
  },
  {
    id: 'financial-edit-cancel',
    categoryId: 'financial',
    title: 'Editar ou cancelar uma despesa',
    summary: 'Uma despesa lançada errada é corrigida pela edição. Uma despesa que não deveria existir é cancelada, com motivo. Nos dois casos, nada é excluído: o histórico sempre fica.',
    steps: [
      'Abra a despesa e clique em "Editar" para corrigir categoria, valor, data, vencimento, veículo, motorista, centro de custo, fornecedor ou forma de pagamento.',
      'Para cancelar, abra a despesa e clique em "Cancelar", informando o motivo.',
    ],
    notes: [
      'Cancelar exige uma permissão própria, diferente da de editar — nem sempre quem corrige um dado pode cancelar uma despesa.',
      'Uma despesa cancelada é definitiva: ela sai dos totais e do orçado x realizado, mas continua visível no histórico, marcada como "Cancelado".',
      'Uma despesa gerada por uma recorrente pode ser editada ou cancelada individualmente, sem afetar o modelo nem as próximas gerações.',
      'Despesas de combustível, manutenção e pneus não aparecem aqui como editáveis: qualquer correção é feita no módulo de origem (abastecimento, ordem de serviço ou operação do pneu).',
    ],
    keywords: ['editar despesa', 'corrigir despesa', 'cancelar despesa'],
    requiredPermission: PERMISSIONS.finance.edit,
    relatedArticleIds: ['financial-expenses', 'financial-payment-status'],
  },
  {
    id: 'financial-payment-status',
    categoryId: 'financial',
    title: 'Situação de pagamento de uma despesa',
    summary: 'A situação (Pendente, Agendado, Parcialmente pago, Pago, Atrasado, Cancelado) é sempre calculada pelo sistema a partir do vencimento e do quanto já foi pago — nunca é escolhida manualmente.',
    whyItMatters: 'Deixar a situação automática evita que ela fique errada no dia seguinte: uma despesa não paga vira "Atrasado" sozinha quando passa do vencimento.',
    steps: [
      'Para registrar que uma despesa foi paga (total ou parcialmente), abra-a e use "Registrar pagamento".',
      'Informe o valor pago e a data do pagamento.',
      'Pagar o valor total deixa a despesa "Pago". Pagar menos deixa "Parcialmente pago".',
    ],
    notes: [
      'Pendente: sem data de vencimento definida.',
      'Agendado: tem vencimento, mas a data ainda não chegou.',
      'Atrasado: o vencimento passou e a despesa ainda não foi totalmente paga.',
      'Parcialmente pago: já recebeu algum pagamento, mas não o valor total.',
      'Pago: o valor total já foi pago.',
      'Cancelado é definitivo — uma despesa cancelada não aceita mais pagamento.',
    ],
    keywords: ['situação', 'status', 'pago', 'atrasado', 'vencido'],
    requiredPermission: PERMISSIONS.finance?.registerpayment,
    relatedArticleIds: ['financial-expenses'],
  },
  {
    id: 'financial-categories',
    categoryId: 'financial',
    title: 'Categorias de despesa',
    summary: 'Categorias organizam os gastos (Seguro, IPVA, Pedágio, Lavagem…) e podem ter subcategorias. Três delas — Combustível, Manutenção e Pneus — são automáticas e não podem ser editadas ou excluídas.',
    whyItMatters: 'Categorizar bem é o que permite comparar "quanto gastamos com pedágio este mês" com precisão, e é a base dos orçamentos.',
    steps: [
      'Em "Financeiro" › "Categorias", crie uma categoria com nome e código.',
      'Opcionalmente, associe a uma categoria-mãe para formar uma hierarquia (ex.: "Custos de veículo" › "Seguro").',
      'Categorias em uso não podem ser excluídas — inative-as.',
    ],
    notes: [
      'As categorias Combustível, Manutenção e Pneus aparecem marcadas como "Automática": seus valores vêm direto dos módulos de combustível, manutenção e pneus. Não é possível lançar uma despesa manual nelas.',
    ],
    keywords: ['categoria de despesa', 'tipo de gasto'],
    requiredPermission: PERMISSIONS.finance?.managecategories,
    relatedArticleIds: ['financial-expenses', 'financial-cost-centers'],
  },
  {
    id: 'financial-cost-centers',
    categoryId: 'financial',
    title: 'Centros de custo',
    summary: 'Um centro de custo é onde a despesa "pertence" — um departamento, uma filial, um projeto. Também podem ter hierarquia (ex.: "Operações" › "Filial Curitiba").',
    whyItMatters: 'Centros de custo permitem separar o gasto por área da empresa, útil quando a frota atende mais de um departamento ou unidade.',
    steps: [
      'Em "Financeiro" › "Centros de custo", crie um centro com código e nome.',
      'Associe a um centro-mãe, se fizer parte de uma hierarquia.',
      'Use o centro de custo ao lançar despesas, recorrentes e orçamentos.',
    ],
    notes: ['Um centro de custo em uso (despesas, orçamentos ou recorrentes) não pode ser excluído — inative-o.'],
    keywords: ['centro de custo', 'departamento', 'filial'],
    requiredPermission: PERMISSIONS.finance?.managecostcenters,
    relatedArticleIds: ['financial-expenses'],
  },
  {
    id: 'financial-recurring',
    categoryId: 'financial',
    title: 'Despesas recorrentes',
    summary: 'Cadastre uma vez uma obrigação que se repete (seguro, financiamento, leasing, assinatura de rastreador…) e o sistema gera a despesa automaticamente, com até 30 dias de antecedência do vencimento.',
    example: 'Descrição: Seguro da frota\nCategoria: Seguro\nValor: R$ 1.200,00\nFrequência: Mensal\nDia do vencimento: 10',
    steps: [
      'Em "Financeiro" › "Recorrentes", crie o modelo com descrição, categoria, valor, frequência (mensal, trimestral, semestral ou anual) e o dia do vencimento no mês.',
      'Defina a data de início e, se a obrigação tiver fim previsto, a data de término.',
      'A partir daí, as despesas aparecem sozinhas em "Despesas", já com vencimento, pouco antes de cada data — sem precisar lançar uma por uma.',
    ],
    notes: [
      'Um modelo que já gerou despesas não pode ser excluído — inative-o para parar a geração.',
      'Mudar o valor do modelo não altera despesas já geradas: vale só a partir da próxima geração.',
    ],
    keywords: ['recorrente', 'assinatura', 'gerar despesa automaticamente'],
    requiredPermission: PERMISSIONS.finance?.managerecurring,
    relatedArticleIds: ['financial-expenses'],
  },
  {
    id: 'financial-budgets',
    categoryId: 'financial',
    title: 'Orçamentos',
    summary: 'Defina quanto espera gastar em uma categoria (por ano ou por mês), por toda a frota, por centro de custo ou por um veículo específico.',
    example: 'Ano: 2027\nCategoria: Combustível\nValor orçado: R$ 150.000,00',
    steps: [
      'Em "Financeiro" › "Orçamentos", escolha o ano (e o mês, se quiser um orçamento mensal em vez de anual).',
      'Escolha a categoria e, se for o caso, o centro de custo ou o veículo.',
      'Informe o valor orçado.',
    ],
    notes: ['Não é possível cadastrar dois orçamentos para o mesmo período, categoria e escopo — edite o existente.'],
    keywords: ['orçamento', 'planejamento de gastos'],
    requiredPermission: PERMISSIONS.finance?.managebudgets,
    relatedArticleIds: ['financial-budget-vs-actual'],
  },
  {
    id: 'financial-budget-vs-actual',
    categoryId: 'financial',
    title: 'Orçado x Realizado',
    summary: 'Compara o que foi orçado com o que foi efetivamente gasto no período: valor orçado, valor realizado, quanto ainda resta e o percentual de utilização.',
    whyItMatters: 'É a forma mais rápida de perceber se uma categoria está estourando o planejado antes de fechar o mês.',
    notes: [
      'Abaixo de 90% do orçado: dentro do orçamento.',
      'De 90% a 100%: próximo do limite.',
      'Acima de 100%: acima do orçamento.',
      'Sem orçamento cadastrado para o período: o sistema mostra isso em vez de um percentual sem sentido.',
      'Uma despesa cancelada não entra na conta do realizado.',
    ],
    keywords: ['orçado x realizado', 'variação', 'utilização do orçamento'],
    requiredPermission: PERMISSIONS.finance?.viewcosts,
    relatedArticleIds: ['financial-budgets'],
  },
  {
    id: 'financial-dashboard',
    categoryId: 'financial',
    title: 'Painel financeiro',
    summary: 'Mostra o custo total da frota no ano, o custo do mês, o custo por km, o gasto por categoria (combustível, manutenção, pneus e demais despesas), a evolução mensal e as despesas em atraso.',
    steps: [
      'Acesse "Financeiro" para ver o painel.',
      'Use os cartões e o gráfico de evolução mensal para entender a tendência de custo da frota.',
      'Clique em uma categoria ou no total para ir direto ao relatório correspondente.',
    ],
    notes: ['Quando falta a permissão de valores de algum módulo (combustível, manutenção, pneus), o painel mostra os números possíveis e avisa que o total é parcial — nunca um total errado em silêncio.'],
    keywords: ['painel financeiro', 'dashboard financeiro'],
    relatedArticleIds: ['financial-vehicle-cost', 'financial-cost-per-km', 'financial-ranking'],
  },
  {
    id: 'financial-vehicle-cost',
    categoryId: 'financial',
    title: 'Custo de um veículo',
    summary: 'A aba "Financeiro" do veículo mostra o custo do mês, o custo por km, o detalhamento por categoria (combustível, manutenção, pneus e outras despesas) e a evolução de custo ao longo do tempo.',
    whyItMatters: 'Permite comparar o custo entre veículos parecidos e identificar aquele que está custando mais do que deveria.',
    steps: [
      'Abra o veículo e clique na aba "Financeiro".',
      'Veja o resumo do mês, o acumulado e o detalhamento por categoria.',
      'Use o gráfico de evolução para ver se o custo está subindo, estável ou caindo.',
      'Role até "Últimas despesas" para ver os lançamentos mais recentes daquele veículo, sem precisar ir até a lista geral de despesas.',
    ],
    keywords: ['custo do veículo', 'gasto por veículo'],
    relatedArticleIds: ['financial-cost-per-km', 'financial-tco', 'fuel-costs', 'tires-costs'],
  },
  {
    id: 'financial-cost-per-km',
    categoryId: 'financial',
    title: 'Custo por quilômetro',
    summary: 'Divide o custo total do período pelos quilômetros realmente rodados no mesmo período, usando o histórico de hodômetro do veículo.',
    whyItMatters: 'Custo por km é a medida que realmente compara veículos com uso diferente: dois veículos podem gastar o mesmo valor, mas um deles roda o dobro.',
    notes: [
      'Quando o histórico de hodômetro do período é curto demais ou está incompleto, o sistema mostra "dados de quilometragem insuficientes" em vez de calcular um número enganoso.',
      'Isso vale tanto para um veículo quanto para o custo por km da frota inteira.',
    ],
    keywords: ['custo por km', 'r$/km', 'custo quilômetro'],
    requiredPermission: PERMISSIONS.finance?.viewcosts,
    relatedArticleIds: ['financial-vehicle-cost'],
  },
  {
    id: 'financial-tco',
    categoryId: 'financial',
    title: 'Custo total de propriedade (TCO)',
    summary: 'Soma o valor de aquisição do veículo com todo o custo operacional acumulado desde a aquisição (combustível, manutenção, pneus e demais despesas), e calcula o custo por mês e por km desde então.',
    whyItMatters: 'O TCO mostra o custo completo de manter um veículo na frota, não só o gasto de um mês — útil para decidir quando trocar um veículo.',
    notes: [
      'É uma análise de gestão operacional da frota, não um cálculo contábil ou fiscal de depreciação.',
      'Quando o veículo não tem data de aquisição cadastrada, o sistema usa a data do cadastro como início.',
      'O custo por km do TCO segue a mesma regra de dados insuficientes do custo por km do período.',
    ],
    keywords: ['tco', 'custo total de propriedade', 'custo de vida do veículo'],
    requiredPermission: PERMISSIONS.finance?.viewcosts,
    relatedArticleIds: ['financial-vehicle-cost', 'financial-cost-per-km'],
  },
  {
    id: 'financial-ranking',
    categoryId: 'financial',
    title: 'Ranking de custos por veículo',
    summary: 'Ordena os veículos da frota por custo total, custo por km, custo de combustível, manutenção, pneus ou número de despesas no período, com filtros por tipo e situação do veículo.',
    whyItMatters: 'Facilita encontrar rapidamente os veículos mais caros da frota e investigar por quê.',
    steps: [
      'Acesse "Financeiro" › "Ranking de veículos".',
      'Escolha o período e, se quiser, filtre por tipo ou situação do veículo.',
      'Clique no cabeçalho de uma coluna para ordenar por ela.',
    ],
    notes: ['Um veículo sem quilometragem suficiente no período aparece com "dados insuficientes" no custo por km, em vez de um número.'],
    keywords: ['ranking', 'veículos mais caros', 'comparar veículos'],
    requiredPermission: PERMISSIONS.finance?.viewcosts,
    relatedArticleIds: ['financial-cost-per-km'],
  },
  {
    id: 'financial-reports',
    categoryId: 'financial',
    title: 'Relatórios financeiros',
    summary: 'Relatório de despesas (com todos os filtros), custo por centro de custo, custo mensal da frota, orçado x realizado e TCO.',
    steps: [
      'Acesse "Financeiro" › "Relatórios" e escolha a aba desejada.',
      'Ajuste o período e os filtros disponíveis em cada relatório.',
    ],
    notes: ['A exportação em Excel/PDF destes relatórios está prevista para uma fase futura — por enquanto, os dados ficam disponíveis na tela.'],
    keywords: ['relatório financeiro', 'exportar relatório'],
    requiredPermission: PERMISSIONS.finance?.viewcosts,
    relatedArticleIds: ['financial-dashboard', 'financial-budget-vs-actual', 'financial-tco'],
  },
];
