import { PERMISSIONS } from '../../../auth/permissions';
import type { HelpArticle, HelpCategory } from '../types';

export const CATEGORY: HelpCategory = {
  id: 'fuel',
  label: 'Combustível',
  description: 'Abastecimentos, consumo, custos, postos, alertas e relatórios de combustível.',
  requiredPermission: PERMISSIONS.fuel.view,
};

export const ARTICLES: HelpArticle[] = [
  {
    id: 'fuel-overview',
    categoryId: 'fuel',
    title: 'Como funciona a gestão de combustível',
    summary: 'Cada abastecimento registra veículo, hodômetro, combustível, quantidade e preço. A partir deles o sistema calcula o total, o consumo, os custos e aponta o que foge do normal.',
    whyItMatters: 'Com os abastecimentos em dia você sabe quanto cada veículo consome, quanto a frota gasta e quais registros merecem uma conferência.',
    steps: [
      'Cadastre os postos onde a frota abastece (e o tanque próprio, se houver).',
      'Informe no cadastro do veículo a capacidade do tanque e, se quiser, o consumo esperado.',
      'Registre cada abastecimento — de preferência no momento, pelo celular.',
      'Acompanhe o painel de Combustível e revise os abastecimentos com alerta.',
    ],
    relatedArticleIds: ['fuel-register', 'fuel-consumption', 'fuel-dashboard'],
  },
  {
    id: 'fuel-register',
    categoryId: 'fuel',
    title: 'Registrar um abastecimento',
    summary: 'Em "Abastecimentos" ou na aba "Combustível" do veículo, clique em "Registrar abastecimento". O total é calculado automaticamente.',
    example: 'Veículo: ABC-1D23\nHodômetro: 125.400 km\nCombustível: Diesel S10\nQuantidade: 250 L\nPreço: R$ 6,20\nTotal: R$ 1.550,00',
    steps: [
      'Escolha o veículo: o sistema mostra o último hodômetro e sugere o combustível, o posto e o motorista alocado.',
      'Digite o hodômetro do painel no momento do abastecimento.',
      'Informe a quantidade e o preço por litro. Se houver preço conhecido para o posto, aparece a opção "usar".',
      'Desligue "Tanque cheio" se foi só um complemento.',
      'Escolha a forma de pagamento e, se quiser, fotografe o cupom.',
      'Salve.',
    ],
    notes: [
      'O hodômetro e o preço nunca vêm preenchidos: são exatamente o que está sendo registrado, então precisam ser digitados.',
      'O hodômetro do abastecimento atualiza a quilometragem do veículo, com as mesmas regras da aba Quilometragem: não pode ser menor que a última leitura.',
      'Abastecimento de veículo inativo não é aceito.',
      'Um abastecimento lançado dias depois, com data anterior a leituras mais recentes, é aceito se o hodômetro couber entre essas leituras.',
    ],
    keywords: ['abastecer', 'lançar abastecimento', 'cupom', 'litros', 'diesel', 'combustível'],
    requiredPermission: PERMISSIONS.fuel.create,
    relatedArticleIds: ['fuel-mobile', 'fuel-anomalies'],
  },
  {
    id: 'fuel-mobile',
    categoryId: 'fuel',
    title: 'Registrar pelo celular',
    summary: 'A tela de abastecimento foi feita para o celular: campos grandes, teclado numérico e foto do cupom pela câmera.',
    steps: [
      'Abra "Abastecimentos" › "Registrar abastecimento".',
      'Confirme o veículo e preencha hodômetro, quantidade e preço.',
      'Toque em "Fotografar cupom" para anexar o comprovante.',
      'Toque em "Salvar abastecimento" na barra fixa no fim da tela.',
    ],
    requiredPermission: PERMISSIONS.fuel.create,
    relatedArticleIds: ['fuel-register'],
  },
  {
    id: 'fuel-consumption',
    categoryId: 'fuel',
    title: 'Como o consumo é calculado',
    summary: 'O consumo é medido de tanque cheio a tanque cheio: km rodados entre dois abastecimentos completos ÷ todo o combustível colocado nesse intervalo.',
    example: 'Tanque cheio com 100.000 km\nTanque cheio com 101.000 km, 200 L\n1.000 km ÷ 200 L = 5,0 km/L',
    whyItMatters: 'Medir só entre tanques cheios evita números enganosos: um complemento sozinho não diz quanto o veículo consumiu.',
    notes: [
      'O primeiro tanque cheio de um veículo ainda não tem consumo: ele é o ponto de partida.',
      'Um abastecimento parcial entra na conta do próximo tanque cheio.',
      'Se no meio do trecho o hodômetro foi corrigido, ou está em revisão, o consumo daquele trecho não é calculado.',
      'Um abastecimento cancelado sai da conta, e o trecho é recalculado.',
      'O valor principal é km/L (ou km/m³ para GNV e km/kWh para recarga elétrica). Na tela do abastecimento também aparece em L/100 km.',
      'A média de um período é ponderada: total de km ÷ total de combustível dos trechos medidos.',
    ],
    keywords: ['km/l', 'média', 'rendimento', 'l/100km', 'tanque cheio'],
    relatedArticleIds: ['fuel-baseline', 'fuel-anomalies'],
  },
  {
    id: 'fuel-baseline',
    categoryId: 'fuel',
    title: 'Consumo esperado de um veículo',
    summary: 'Cada trecho medido é comparado com um consumo esperado: o configurado no veículo, ou a média do próprio veículo, ou a média dos veículos do mesmo tipo.',
    notes: [
      'O consumo esperado configurado no cadastro do veículo vale mais que as médias.',
      'Sem ele, o sistema usa a média dos últimos trechos do próprio veículo (a partir de 3 trechos medidos).',
      'Sem histórico suficiente, usa a média dos veículos do mesmo tipo (a partir de 5 trechos medidos nos últimos 180 dias).',
      'O esperado usado em cada trecho fica guardado: mudar o cadastro depois não altera os trechos já calculados.',
    ],
    relatedArticleIds: ['fuel-consumption', 'fuel-thresholds'],
  },
  {
    id: 'fuel-anomalies',
    categoryId: 'fuel',
    title: 'Alertas de abastecimento e como revisar',
    summary: 'Quando algo foge do padrão, o abastecimento é salvo normalmente e fica "Requer revisão". Um alerta pede conferência — não significa erro nem irregularidade.',
    example: 'Quantidade: 520 L\nTanque cadastrado: 400 L\n→ "Quantidade acima do tanque" — revisão recomendada',
    steps: [
      'Abra o abastecimento (pelo painel de Combustível ou filtrando "Requer revisão").',
      'Leia o motivo do alerta e confira o comprovante, o hodômetro e a quantidade.',
      'Escolha: "Revisar" se os dados estão corretos, "Corrigir" se algo foi digitado errado, ou "Cancelar" se o registro não deveria existir.',
    ],
    notes: [
      'Tipos de alerta: quantidade acima da capacidade do tanque, preço fora da média, hodômetro em revisão, abastecimentos muito próximos, combustível diferente do cadastro do veículo e consumo abaixo ou acima do esperado.',
      'Consumo acima do esperado costuma indicar um abastecimento não registrado ou hodômetro digitado errado no período.',
      'Um alerta de consumo nunca abre manutenção sozinho. Se for o caso, abra uma solicitação de manutenção depois de conferir.',
      'Revisar um abastecimento com hodômetro em revisão também confirma a leitura de hodômetro — por isso exige a permissão de revisar leituras.',
    ],
    keywords: ['suspeito', 'anomalia', 'alerta', 'revisão', 'fraude', 'conferir'],
    relatedArticleIds: ['fuel-correction', 'fuel-thresholds'],
  },
  {
    id: 'fuel-correction',
    categoryId: 'fuel',
    title: 'Corrigir ou cancelar um abastecimento',
    summary: 'Abastecimentos não são excluídos. Um dado errado é corrigido com motivo, e um registro indevido é cancelado — os dois ficam no histórico.',
    steps: [
      'Abra o abastecimento e clique em "Corrigir".',
      'Altere o que estava errado e informe o motivo.',
      'Salve: a correção mostra quem corrigiu, quando, o motivo e cada valor anterior e novo.',
    ],
    notes: [
      'O total, o consumo e os alertas são recalculados depois da correção.',
      'Se o abastecimento já atualizou o hodômetro do veículo, corrigir o km gera uma correção de hodômetro auditada (exige a permissão de corrigir hodômetro) e só é possível enquanto não houver leituras posteriores.',
      'A data de um abastecimento que gerou leitura de hodômetro não muda: cancele e registre de novo com a data certa.',
      'Para trocar o veículo, cancele e registre novamente.',
      'Um abastecimento cancelado não entra em totais nem no consumo.',
    ],
    requiredPermission: PERMISSIONS.fuel.correct,
    relatedArticleIds: ['fuel-anomalies'],
  },
  {
    id: 'fuel-costs',
    categoryId: 'fuel',
    title: 'Custos de combustível e custo por km',
    summary: 'O custo total soma o valor de cada abastecimento do período. O custo por km divide o gasto dos trechos medidos pelos km desses trechos.',
    example: 'Combustível: R$ 20.000\nDistância medida: 10.000 km\nCusto/km: R$ 2,00',
    notes: [
      'São valores operacionais para acompanhar a frota, não valores contábeis.',
      'O preço pago fica gravado em cada abastecimento e nunca é recalculado pelo preço de hoje.',
      'Os valores em reais só aparecem para quem tem permissão de ver custos de combustível. Quem registra um abastecimento sempre vê os valores do que registrou.',
    ],
    keywords: ['gasto', 'custo/km', 'valor', 'dinheiro'],
    requiredPermission: PERMISSIONS.fuel.viewcosts,
    relatedArticleIds: ['fuel-reports'],
  },
  {
    id: 'fuel-dashboard',
    categoryId: 'fuel',
    title: 'Painel de Combustível',
    summary: 'Em "Combustível" você vê, para o período escolhido, o custo total, os litros, o preço médio, o consumo médio, o custo por km e os abastecimentos que requerem atenção.',
    notes: [
      'Escolha o período pelos atalhos (30 dias, 90 dias, 12 meses) ou pelas datas.',
      'Os gráficos têm o botão "Ver tabela" com todos os números.',
      'As comparações entre veículos sempre dizem qual medida e qual período estão usando.',
      'O painel inicial também mostra os abastecimentos que requerem revisão, para quem pode revisá-los.',
    ],
    relatedArticleIds: ['fuel-reports', 'fuel-anomalies'],
  },
  {
    id: 'fuel-vehicle-tab',
    categoryId: 'fuel',
    title: 'Combustível na página do veículo',
    summary: 'A aba "Combustível" do veículo reúne o consumo médio comparado ao esperado, o custo por km, o histórico por dia, semana ou mês e os últimos abastecimentos.',
    notes: ['Períodos sem trecho medido aparecem sem consumo ("—") em vez de um número estimado.'],
    relatedArticleIds: ['fuel-consumption'],
  },
  {
    id: 'fuel-reports',
    categoryId: 'fuel',
    title: 'Relatórios de combustível',
    summary: 'Em "Combustível" › "Relatórios de combustível": abastecimentos, consumo por veículo, custos (por veículo, motorista, posto ou combustível), postos e preços por mês.',
    notes: [
      'Todos os relatórios usam o período escolhido, podem ser ordenados pelo cabeçalho e são paginados.',
      'O relatório de consumo mostra a variação em relação ao esperado de cada trecho.',
      'Os relatórios de custos e de preços aparecem só para quem pode ver custos.',
      'A exportação para Excel/PDF ainda não está disponível.',
    ],
    relatedArticleIds: ['fuel-costs'],
  },
  {
    id: 'fuel-stations',
    categoryId: 'fuel',
    title: 'Postos de combustível e preços de referência',
    summary: 'Cadastre os postos usados pela frota — inclusive o tanque próprio da empresa — e, se quiser, o preço praticado ou negociado em cada um.',
    steps: [
      'Acesse "Postos de combustível" e clique em "Novo posto".',
      'Informe nome e, se quiser, CNPJ, endereço e contato. Marque "Tanque próprio" para a bomba interna.',
      'Na página do posto, registre o preço de referência de cada combustível e a data a partir da qual vale.',
    ],
    notes: [
      'O preço de referência aparece como sugestão no registro e é usado para apontar preços fora do normal.',
      'Um posto com abastecimentos não é excluído: inative-o.',
      'O controle de estoque do tanque próprio ainda não faz parte do sistema.',
    ],
    requiredPermission: PERMISSIONS.fuel.managestations,
    relatedArticleIds: ['fuel-types'],
  },
  {
    id: 'fuel-types',
    categoryId: 'fuel',
    title: 'Tipos de combustível',
    summary: 'A lista de combustíveis (Diesel S10, Gasolina, Etanol, GNV…) é configurável em "Configurações" › "Combustível".',
    notes: [
      'Cada empresa começa com uma lista padrão e pode criar, editar e inativar combustíveis.',
      'A unidade (L, m³ ou kWh) não muda depois que o combustível foi usado, porque mudaria o sentido do consumo já calculado.',
      'O combustível cadastrado no veículo (ex.: Flex) é diferente: ele diz o que o motor aceita e serve para alertar um combustível incompatível.',
    ],
    requiredPermission: PERMISSIONS.fuel.configure,
    relatedArticleIds: ['fuel-thresholds'],
  },
  {
    id: 'fuel-thresholds',
    categoryId: 'fuel',
    title: 'Limites dos alertas',
    summary: 'Em "Configurações" › "Combustível" você ajusta quanto um abastecimento pode fugir do padrão antes de gerar alerta.',
    example: 'Tolerância do tanque: 5%\nVariação de preço: 20%\nVariação de consumo: 20%\nIntervalo mínimo: 2 h',
    notes: [
      'Mudar um limite vale para os próximos registros e recálculos; os resultados já calculados ficam como estavam.',
      'Também é possível exigir o motorista em todo abastecimento.',
    ],
    requiredPermission: PERMISSIONS.fuel.configure,
    relatedArticleIds: ['fuel-anomalies'],
  },
];
