import { PERMISSIONS } from '../../../auth/permissions';
import type { HelpArticle, HelpCategory } from '../types';

export const CATEGORY: HelpCategory = {
  id: 'tires',
  label: 'Pneus',
  description: 'Cadastro pelo número de fogo, instalação, rodízio, inspeção, sulco, consertos, recapagens, custos e baixa.',
  requiredPermission: PERMISSIONS.tires.view,
};

export const ARTICLES: HelpArticle[] = [
  {
    id: 'tires-overview',
    categoryId: 'tires',
    title: 'Como funciona a gestão de pneus',
    summary: 'Cada pneu é cadastrado individualmente, com número de fogo próprio, e o sistema acompanha toda a vida dele: em que veículo e posição está, quanto rodou, quanto sulco tem e quanto já custou.',
    whyItMatters: 'O mesmo pneu passa por vários veículos, rodízios, consertos e recapagens. Com o histórico completo você sabe onde ele está, se ainda vale a pena usá-lo e quanto ele custa por quilômetro.',
    steps: [
      'Confira as configurações de eixos dos veículos e implementos (aba Pneus de cada um).',
      'Cadastre os modelos de pneu usados pela frota e depois cada pneu, pelo número de fogo.',
      'Instale os pneus nas posições pelo diagrama da aba Pneus do veículo.',
      'Inspecione periodicamente: sulco, pressão, desgaste e danos.',
      'Registre remoções, rodízios, consertos, recapagens e a baixa no fim da vida.',
      'Acompanhe o Painel de pneus e os alertas.',
    ],
    example: 'PN-000123 · Michelin X Multi Z 295/80R22.5\nInstalado em ABC-1D23, Eixo 1 — Esquerdo\nSulco 9 mm · 72.400 km rodados · 1 recapagem',
    keywords: ['pneu', 'pneus', 'borracharia', 'gestão de pneus', 'ciclo de vida'],
    relatedArticleIds: ['tires-register', 'tires-layout', 'tires-install', 'tires-statuses'],
  },
  {
    id: 'tires-statuses',
    categoryId: 'tires',
    title: 'Situações do pneu',
    summary: 'Todo pneu está em uma situação: Em estoque, Instalado, Em avaliação, Em conserto, Em recapagem ou Baixado. As mudanças acontecem pelas operações, nunca por edição.',
    steps: [
      'Em estoque: disponível para instalar.',
      'Instalado: está em uma posição de um veículo ou implemento.',
      'Em avaliação: foi retirado e aguarda uma decisão (voltar ao estoque, mandar consertar, recapar ou dar baixa).',
      'Em conserto / Em recapagem: está no fornecedor.',
      'Baixado: fim definitivo (fim de vida, dano irreparável, venda, extravio, transferência). Não volta a ser instalado.',
    ],
    notes: [
      'Vendido, extraviado ou descartado são motivos da baixa, não situações diferentes.',
      'Um pneu recapado volta para "Em estoque"; o número de recapagens fica registrado no pneu.',
    ],
    keywords: ['status', 'estoque', 'disponível', 'avaliação', 'baixado'],
    relatedArticleIds: ['tires-overview', 'tires-disposal'],
  },
  {
    id: 'tires-register',
    categoryId: 'tires',
    title: 'Cadastrar um pneu',
    summary: 'Em Pneus › "Cadastrar pneu", escolha o modelo e informe o número de fogo (ou deixe o sistema gerar), o DOT e os dados de compra.',
    steps: [
      'Clique em "Cadastrar pneu".',
      'Deixe o número de fogo em branco para o sistema gerar (PN-000001…) ou digite o número que a empresa já usa.',
      'Escolha o modelo (marca, modelo e medida). Se ele não existir, use "Cadastrar novo modelo".',
      'Digite o DOT: a data de fabricação é preenchida a partir dos quatro últimos números.',
      'Informe a data e o valor da compra e o fornecedor.',
      'Informe o local de armazenamento e salve. O pneu entra como "Em estoque".',
    ],
    example: 'DOT 4B7X 3524 → fabricado na semana 35 de 2024',
    notes: [
      'Para pneus que já estavam em uso antes do sistema, marque "Este pneu já foi usado" e informe o sulco atual e as recapagens já feitas.',
      'O valor de compra só aparece e só pode ser informado por quem tem permissão para ver custos de pneus.',
      'Um pneu com histórico não pode ser excluído: dê baixa nele.',
    ],
    keywords: ['número de fogo', 'dot', 'novo pneu', 'cadastro', 'série', 'modelo de pneu'],
    requiredPermission: PERMISSIONS.tires.create,
    relatedArticleIds: ['tires-overview', 'tires-install'],
  },
  {
    id: 'tires-layout',
    categoryId: 'tires',
    title: 'Diagrama de pneus do veículo',
    summary: 'A aba Pneus do veículo (e a seção Pneus do implemento) mostra o veículo visto de cima, com cada posição, o pneu instalado, o sulco e um ícone da situação.',
    steps: [
      'Abra o veículo e vá à aba "Pneus".',
      'Toque numa posição: ao lado aparecem o número de fogo, a marca, o sulco, os km, a data da instalação, a última inspeção e os alertas.',
      'Use os botões do detalhe para inspecionar, remover, substituir ou transferir.',
      'Numa posição vazia, use "Instalar pneu".',
    ],
    notes: [
      'Cada posição mostra um ícone e um texto, não só a cor: ✓ sulco normal, ⚠ perto do mínimo, ⛔ requer ação, ? sulco não medido, círculo tracejado = vazia.',
      'No celular o diagrama vira uma lista por eixo, sem precisar dar zoom.',
      'Os códigos das posições seguem o eixo e o lado: 1E (eixo 1, esquerdo), 2EE (eixo 2, esquerdo externo), 2EI (esquerdo interno), EST1 (estepe).',
    ],
    keywords: ['diagrama', 'posição', 'eixo', 'mapa de pneus', 'layout'],
    relatedArticleIds: ['tires-axle-configuration', 'tires-install', 'tires-inspect'],
  },
  {
    id: 'tires-axle-configuration',
    categoryId: 'tires',
    title: 'Configuração de eixos',
    summary: 'A configuração de eixos diz quantos eixos e pneus um veículo ou implemento tem. As posições do diagrama são geradas a partir dela.',
    steps: [
      'Na aba Pneus de um veículo sem configuração, escolha uma configuração e clique em "Usar configuração".',
      'Para criar ou ajustar configurações, vá em Configurações › Pneus › "Configurações de eixos".',
      'Para cada eixo, informe o tipo (direcional, tração, livre, implemento), se é rodado duplo e se é obrigatório.',
      'Opcionalmente, informe a medida exigida e a pressão de referência do eixo.',
      'Confira a pré-visualização e salve.',
    ],
    notes: [
      'Toda empresa começa com configurações prontas: carro/picape, caminhão toco 4x2, truck 6x2, cavalo mecânico 6x2 e 6x4, semirreboques de 2 e 3 eixos.',
      'Com a medida exigida configurada, o sistema impede instalar pneu de outra medida. Sem ela, avisa que a compatibilidade não pôde ser verificada.',
      'Não é possível tirar de uma configuração uma posição que tem pneu instalado.',
    ],
    keywords: ['eixos', 'configuração', 'rodado duplo', 'cavalo', 'semirreboque', 'estepe'],
    requiredPermission: PERMISSIONS.tires.managesettings,
    relatedArticleIds: ['tires-layout', 'tires-pressure'],
  },
  {
    id: 'tires-install',
    categoryId: 'tires',
    title: 'Instalar um pneu',
    summary: 'Na aba Pneus do veículo, toque numa posição vazia e em "Instalar pneu", ou abra o pneu e use "Instalar". O km da instalação vem do hodômetro do veículo.',
    steps: [
      'Escolha a posição vazia no diagrama e clique em "Instalar pneu".',
      'Selecione um pneu em estoque (se a posição exige uma medida, só aparecem pneus dela).',
      'Confira o aviso de compatibilidade.',
      'Se o pneu foi instalado antes, informe quando. Se tiver o hodômetro de agora, informe-o — ele entra no histórico de quilometragem.',
      'Clique em "Instalar pneu".',
    ],
    notes: [
      'Só pneus "Em estoque" são instalados. Um pneu instalado em outro veículo usa "Transferir".',
      'Uma posição ocupada não é substituída sem querer: use "Substituir", que registra a remoção do pneu atual.',
      'Se o hodômetro informado for um aumento suspeito, a instalação é recusada: registre a leitura na aba Quilometragem para revisão.',
      'Em implementos o km não é medido (o implemento não tem hodômetro).',
    ],
    keywords: ['montar pneu', 'colocar pneu', 'instalação', 'compatibilidade', 'medida'],
    requiredPermission: PERMISSIONS.tires.install,
    relatedArticleIds: ['tires-replace', 'tires-layout', 'tires-mileage'],
  },
  {
    id: 'tires-remove',
    categoryId: 'tires',
    title: 'Remover um pneu',
    summary: 'No detalhe da posição, "Mais ações" › "Remover". Informe o motivo e o destino: estoque, avaliação, conserto, recapagem ou baixa.',
    steps: [
      'Selecione o pneu no diagrama e escolha "Remover".',
      'Escolha o motivo (inspeção, dano, recapagem, fim de vida…) e o destino do pneu.',
      'Se medir, informe o sulco, a pressão, a condição e os danos: a medição entra no histórico do pneu.',
      'Para conserto ou recapagem, informe o fornecedor se já souber.',
      'Para baixa, informe o motivo da baixa e anexe o documento, se houver.',
      'Clique em "Remover pneu".',
    ],
    example: 'Motivo: Recapagem · Destino: Recapagem\nO pneu fica "Em recapagem" e o envio aparece em "Consertos e recapagens".',
    notes: [
      'Os km rodados naquela posição são calculados pelo hodômetro do veículo e somados à vida do pneu.',
      'Destino "Baixa" é definitivo e exige a permissão de dar baixa.',
    ],
    keywords: ['retirar pneu', 'desmontar', 'remoção', 'destino'],
    requiredPermission: PERMISSIONS.tires.remove,
    relatedArticleIds: ['tires-replace', 'tires-retread', 'tires-disposal'],
  },
  {
    id: 'tires-replace',
    categoryId: 'tires',
    title: 'Substituir um pneu',
    summary: 'A substituição tira o pneu da posição e coloca outro numa única operação, registrando a remoção do antigo com motivo e destino.',
    steps: [
      'Selecione o pneu no diagrama e escolha "Substituir".',
      'Escolha o pneu que vai entrar (em estoque, da medida da posição).',
      'Informe o motivo e o destino do pneu que sai e, se quiser, a medição dele.',
      'Clique em "Substituir pneu".',
    ],
    notes: [
      'Se algo impedir a instalação do novo pneu (medida incompatível, por exemplo), nada é gravado: o pneu antigo continua no lugar.',
      'Os dois pneus ganham o registro no histórico.',
    ],
    keywords: ['trocar pneu', 'troca', 'substituição'],
    requiredPermission: PERMISSIONS.tires.install,
    relatedArticleIds: ['tires-remove', 'tires-install'],
  },
  {
    id: 'tires-transfer',
    categoryId: 'tires',
    title: 'Transferir um pneu para outro veículo',
    summary: 'Para levar um pneu instalado direto para outro veículo ou implemento, use "Transferir": ele sai de uma posição e entra na outra numa única operação.',
    steps: [
      'No detalhe da posição (ou na página do pneu), escolha "Transferir para outro veículo".',
      'Escolha o veículo ou implemento de destino e a posição livre.',
      'Opcionalmente, informe os hodômetros de origem e de destino.',
      'Clique em "Transferir pneu".',
    ],
    requiredPermission: PERMISSIONS.tires.install,
    relatedArticleIds: ['tires-rotation', 'tires-history'],
  },
  {
    id: 'tires-rotation',
    categoryId: 'tires',
    title: 'Fazer rodízio de pneus',
    summary: 'Na aba Pneus do veículo, "Fazer rodízio": escolha a nova posição de cada pneu. Tudo é gravado de uma vez — ou o rodízio inteiro é registrado, ou nada muda.',
    steps: [
      'Clique em "Fazer rodízio".',
      'Para cada pneu, escolha a nova posição (os que não mudam ficam como estão).',
      'Confira os avisos: duas posições iguais ou uma posição ocupada por pneu que não faz parte do rodízio impedem o registro.',
      'Informe quando foi feito, o hodômetro (opcional) e o motivo.',
      'Clique em "Registrar rodízio".',
    ],
    example: 'Antes: A → 1E, B → 1D, C → 2EE, D → 2DE\nDepois: A → 2EE, B → 2DE, C → 1E, D → 1D',
    notes: [
      'Os km rodados por cada pneu até o rodízio continuam com ele.',
      'O rodízio aparece no histórico de cada pneu e no histórico do veículo.',
      'Pode-se trocar o estepe com uma posição: o estepe não soma km enquanto está guardado.',
    ],
    keywords: ['rodízio', 'trocar posição', 'inverter pneus'],
    requiredPermission: PERMISSIONS.tires.rotate,
    relatedArticleIds: ['tires-layout', 'tires-history'],
  },
  {
    id: 'tires-inspect',
    categoryId: 'tires',
    title: 'Inspecionar um pneu',
    summary: 'Toque na posição e em "Inspecionar". Registre sulco, pressão, condição visual, desgaste observado, danos e fotos — funciona bem no celular.',
    steps: [
      'Selecione o pneu no diagrama e toque em "Inspecionar".',
      'Meça o sulco (a menor medida entre os canais) e digite em milímetros.',
      'Meça a pressão e escolha a unidade (psi, bar ou kPa).',
      'Escolha a condição: Bom, Atenção ou Impróprio para uso.',
      'Marque o desgaste observado e os danos encontrados.',
      'Tire fotos e salve a inspeção.',
    ],
    notes: [
      'Enquanto você digita, a tela mostra se o sulco está perto do mínimo e se a pressão está fora da referência do eixo.',
      'Nenhuma medição é sobrescrita: cada inspeção fica no histórico do pneu.',
      'Registre o que viu. O sistema não diagnostica a causa (alinhamento, suspensão…): isso é avaliado depois.',
      'Se a empresa ligou a regra, um pneu "Impróprio para uso" em veículo abre automaticamente uma solicitação de manutenção.',
    ],
    keywords: ['inspeção', 'medir sulco', 'calibrar', 'foto do pneu', 'dano', 'desgaste'],
    requiredPermission: PERMISSIONS.tires.inspect,
    relatedArticleIds: ['tires-tread', 'tires-pressure', 'tires-alerts', 'tires-from-occurrence'],
  },
  {
    id: 'tires-tread',
    categoryId: 'tires',
    title: 'Sulco do pneu',
    summary: 'O sulco é a profundidade dos canais da banda de rodagem, em milímetros. O sistema guarda cada medição e compara com os limites definidos pela sua empresa.',
    example: '01/09 — 14 mm\n15/09 — 12 mm\n01/10 — 10 mm\n15/10 — 8 mm',
    notes: [
      'O "sulco mínimo" e o "aviso de sulco" são a política da empresa (Configurações › Pneus). Eles não substituem as exigências legais nem as recomendações do fabricante.',
      'Se o sulco cair mais rápido que a referência configurada entre duas medições, o pneu fica marcado como "requer revisão".',
      'Depois de uma recapagem, o sulco da banda nova passa a ser o sulco atual.',
    ],
    keywords: ['sulco', 'profundidade', 'desgaste', 'twi', 'mm', 'banda'],
    relatedArticleIds: ['tires-inspect', 'tires-alerts', 'tires-settings'],
  },
  {
    id: 'tires-pressure',
    categoryId: 'tires',
    title: 'Pressão dos pneus',
    summary: 'A pressão medida na inspeção é comparada com a pressão de referência do eixo, com a tolerância configurada pela empresa.',
    steps: [
      'Configure a pressão de referência por eixo em Configurações › Pneus › Configurações de eixos.',
      'Configure a unidade padrão e a tolerância em Configurações › Pneus › Limites e alertas.',
      'Na inspeção, informe a pressão e a unidade usada no calibrador.',
    ],
    notes: [
      'Sem pressão de referência no eixo, a medida é guardada, mas aparece como "Sem referência" — o sistema não adivinha.',
      'A pressão é informada manualmente; sensores automáticos (TPMS) não estão integrados.',
    ],
    keywords: ['calibragem', 'psi', 'bar', 'kpa', 'pressão'],
    relatedArticleIds: ['tires-inspect', 'tires-axle-configuration'],
  },
  {
    id: 'tires-repair',
    categoryId: 'tires',
    title: 'Consertos de pneu',
    summary: 'Um pneu fora do veículo é enviado para conserto e, ao voltar, você conclui o serviço com o resultado. Um furo consertado no próprio veículo é registrado direto, sem remover o pneu.',
    steps: [
      'Pneu em estoque ou em avaliação: na página do pneu, "Ações" › "Enviar para conserto".',
      'Pneu instalado com furo consertado na hora: "Registrar conserto no veículo".',
      'Ao receber o pneu de volta, clique em "Concluir conserto": aprovado (volta ao estoque) ou reprovado (aguarda decisão).',
      'Informe o valor, a garantia e anexe a nota, se houver.',
    ],
    notes: [
      'O fornecedor pode ser uma oficina cadastrada ou um nome digitado.',
      'Vários consertos ou furos num período curto deixam o pneu marcado como "requer revisão".',
    ],
    keywords: ['conserto', 'furo', 'vulcanização', 'borracharia', 'reparo'],
    requiredPermission: PERMISSIONS.tires.repair,
    relatedArticleIds: ['tires-retread', 'tires-costs'],
  },
  {
    id: 'tires-retread',
    categoryId: 'tires',
    title: 'Recapagem',
    summary: 'Envie o pneu para recapagem (na remoção, com destino "Recapagem", ou pela página do pneu) e, quando voltar, registre se a carcaça foi aprovada, a banda aplicada e o sulco novo.',
    steps: [
      'Remova o pneu com destino "Recapagem" ou use "Enviar para recapagem".',
      'O pneu fica "Em recapagem", com o número da recapagem (1ª, 2ª…).',
      'Ao receber de volta, clique em "Concluir recapagem".',
      'Aprovado: informe o sulco da banda nova (obrigatório), a banda, o valor e a garantia. O pneu volta ao estoque.',
      'Reprovado: informe o motivo (ex.: carcaça sem condição). O pneu fica em avaliação para você decidir.',
    ],
    example: 'Original → Recapagem nº 1 → Recapagem nº 2 → Baixa',
    notes: ['Quem decide se o pneu pode ser recapado é o fornecedor ou o gestor: o sistema só registra a decisão.'],
    keywords: ['recapagem', 'recauchutagem', 'banda', 'carcaça', 'recapar'],
    requiredPermission: PERMISSIONS.tires.retread,
    relatedArticleIds: ['tires-remove', 'tires-costs', 'tires-tread'],
  },
  {
    id: 'tires-history',
    categoryId: 'tires',
    title: 'Histórico do pneu',
    summary: 'A página do pneu reúne toda a vida dele: linha do tempo, instalações (com km por posição), inspeções, consertos e recapagens, custos e anexos.',
    steps: [
      'Abra o pneu pela lista de Pneus ou tocando no número de fogo no diagrama.',
      'Use as abas: Histórico, Instalações, Inspeções, Consertos e recapagens, Custos e Anexos.',
    ],
    example: 'PN-000123\n01/01 — Cadastrado\n10/01 — Instalado em ABC-1D23, Eixo 1 — Esquerdo\n10/05 — Rodízio para Eixo 2 — Direito externo\n20/08 — Removido para recapagem\n01/09 — Recapagem nº 1 concluída\n05/09 — Instalado em DEF-5G67',
    notes: [
      'O histórico não é apagado nem reescrito. Se o km de uma instalação foi lançado errado, quem tem permissão usa o lápis em "Instalações" para corrigir, com motivo — a correção também aparece no histórico.',
      'As movimentações aparecem também no histórico do veículo.',
    ],
    keywords: ['linha do tempo', 'movimentação', 'vida do pneu', 'histórico'],
    relatedArticleIds: ['tires-overview', 'tires-costs'],
  },
  {
    id: 'tires-mileage',
    categoryId: 'tires',
    title: 'Quilometragem do pneu',
    summary: 'O km do pneu vem do hodômetro do veículo: a diferença entre o km da instalação e o da remoção, somada em todas as posições por onde ele passou.',
    notes: [
      'Não existe um hodômetro separado para o pneu: o histórico de quilometragem do veículo é a fonte.',
      'O estepe não soma km enquanto está guardado.',
      'Em implementos o km não é medido; o pneu fica marcado com "período sem km medido" e o custo por km não é exibido.',
      'Uma operação lançada depois usa o km que o histórico tinha naquela data.',
    ],
    keywords: ['km do pneu', 'quilometragem', 'hodômetro', 'rodagem'],
    relatedArticleIds: ['tires-install', 'tires-costs'],
  },
  {
    id: 'tires-costs',
    categoryId: 'tires',
    title: 'Custos do pneu e custo por km',
    summary: 'O custo do ciclo de vida soma compra, consertos, recapagens e outros custos (montagem, balanceamento). Dividido pelos km rodados, dá o custo por km.',
    example: 'Compra R$ 2.000 + conserto R$ 150 + recapagem R$ 600 + montagem R$ 50 = R$ 2.800\n100.000 km rodados → R$ 0,0280/km',
    notes: [
      'O custo por km só aparece depois de 5.000 km medidos e quando todo o km do pneu é conhecido: antes disso o número engana.',
      'Consertos e recapagens entram sozinhos ao concluir o serviço. Montagem e outros custos são registrados em "Ações" › "Registrar custo".',
      'Os valores só aparecem para quem tem permissão para ver custos de pneus. São valores operacionais, não contábeis.',
    ],
    keywords: ['cpk', 'custo por km', 'custo', 'valor', 'gasto'],
    requiredPermission: PERMISSIONS.tires.viewcosts,
    relatedArticleIds: ['tires-reports', 'tires-mileage'],
  },
  {
    id: 'tires-disposal',
    categoryId: 'tires',
    title: 'Dar baixa em um pneu',
    summary: 'No fim da vida (ou em caso de venda, extravio ou dano irreparável), dê baixa no pneu: ele sai do estoque de forma definitiva e o histórico é mantido.',
    steps: [
      'Pneu instalado: remova-o com destino "Baixa".',
      'Pneu em estoque ou em avaliação: na página do pneu, "Ações" › "Dar baixa".',
      'Informe o motivo, o destino (reciclagem, comprador…) e a condição.',
      'Anexe o documento da baixa, se houver, e confirme.',
    ],
    notes: [
      'Um pneu baixado nunca fica instalado e não volta a ser instalado.',
      'Se a empresa configurou uma vida mínima esperada, um pneu baixado antes desse km fica marcado como "requer revisão".',
    ],
    keywords: ['baixa', 'descarte', 'sucata', 'venda de pneu', 'fim de vida', 'reciclagem'],
    requiredPermission: PERMISSIONS.tires.dispose,
    relatedArticleIds: ['tires-statuses', 'tires-remove'],
  },
  {
    id: 'tires-alerts',
    categoryId: 'tires',
    title: 'Alertas e "requer revisão"',
    summary: 'O sistema avisa quando o sulco está perto ou no mínimo da empresa, a inspeção está atrasada, há dano ou desgaste irregular, a pressão está fora da referência ou o pneu passou da idade configurada.',
    steps: [
      'Veja os alertas no diagrama do veículo, na página do pneu e no Painel de pneus.',
      'Sinais calculados (perda rápida de sulco, consertos ou furos repetidos, vida curta, danos repetidos na mesma posição) aparecem como "requer revisão".',
      'Depois de conferir, use "Marcar como revisado" e descreva o que verificou.',
    ],
    notes: [
      'Os alertas usam os limites da sua empresa e não são uma determinação legal.',
      'Um alerta não indica a causa: ele pede uma conferência.',
      'Nenhum alerta abre manutenção sozinho, a não ser que a empresa ligue a regra para pneus impróprios.',
    ],
    keywords: ['alerta', 'aviso', 'revisão', 'anomalia', 'inspeção atrasada'],
    relatedArticleIds: ['tires-tread', 'tires-settings', 'tires-dashboard'],
  },
  {
    id: 'tires-from-occurrence',
    categoryId: 'tires',
    title: 'Problema de pneu no checklist ou numa ocorrência',
    summary: 'Um item de pneu reprovado no checklist vira uma ocorrência do tipo "Pneu". Na ocorrência, o botão "Inspecionar pneus do veículo" leva direto ao diagrama.',
    steps: [
      'Abra a ocorrência de pneu.',
      'Clique em "Inspecionar pneus do veículo".',
      'Inspecione a posição afetada e, se precisar, remova ou substitua o pneu.',
      'Se for preciso oficina, use "Abrir solicitação de manutenção" na ocorrência.',
    ],
    relatedArticleIds: ['tires-inspect', 'tires-replace'],
  },
  {
    id: 'tires-dashboard',
    categoryId: 'tires',
    title: 'Painel de pneus',
    summary: 'O Painel de pneus mostra quantos pneus estão instalados, em estoque, em avaliação, em conserto e em recapagem, o que requer atenção, os de maior custo por km e as movimentações recentes.',
    steps: [
      'Abra "Painel de pneus" no menu.',
      'Clique em qualquer número para ver a lista de pneus já filtrada.',
      'Use "Próximas inspeções" para planejar a semana.',
    ],
    keywords: ['painel', 'indicadores', 'dashboard'],
    relatedArticleIds: ['tires-reports', 'tires-alerts'],
  },
  {
    id: 'tires-reports',
    categoryId: 'tires',
    title: 'Relatórios de pneus',
    summary: 'Em "Painel de pneus" › "Relatórios": inventário, ciclo de vida (instalações e km), inspeções e custos, com filtros e ordenação.',
    notes: [
      'O relatório de custos mostra o custo do ciclo de vida de cada pneu; o período filtra os pneus comprados nele.',
      'Os relatórios ainda não têm exportação para Excel ou PDF.',
    ],
    keywords: ['relatório', 'inventário', 'ciclo de vida', 'inspeções'],
    relatedArticleIds: ['tires-dashboard', 'tires-costs'],
  },
  {
    id: 'tires-settings',
    categoryId: 'tires',
    title: 'Limites e configurações de pneus',
    summary: 'Em Configurações › Pneus você define a política da empresa: sulco mínimo e de aviso, intervalo de inspeção, idade para revisão, tolerância e unidade de pressão, perda de sulco para revisão e vida mínima esperada.',
    notes: [
      'Os limites valem para os próximos alertas; as datas (inspeção atrasada, idade) são recalculadas na hora.',
      'A regra "abrir solicitação de manutenção quando um pneu for inspecionado como impróprio" vem desligada.',
      'Os valores padrão (3 mm de mínimo, 4 mm de aviso, inspeção a cada 30 dias, 5 anos de idade) são sugestões: ajuste à sua operação.',
    ],
    keywords: ['configuração', 'limite', 'política', 'parâmetros'],
    requiredPermission: PERMISSIONS.tires.managesettings,
    relatedArticleIds: ['tires-axle-configuration', 'tires-alerts'],
  },
];
