// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REC4.Infrastructure.Data;

#nullable disable

namespace REC4.Infrastructure.Data.Migrations
{
    [DbContext(typeof(Rec4DbContext))]
    [Migration("20260928132303_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("REC4.Domain.Entities.ContaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DigitoConta")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContasBancarias_PessoaId_Principal")
                        .HasFilter("[IsPrincipal] = 1");

                    b.ToTable("ContasBancarias", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique()
                        .HasDatabaseName("IX_Enderecos_PessoaId_Principal")
                        .HasFilter("[IsPrincipal] = 1");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Perfis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Cliente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Fornecedor"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Parceiro"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Colaborador"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Emitente"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Seguradora"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Proprietário"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Corretora"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Reguladora"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Responsável Financeiro"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Agenciador"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Motorista"
                        });
                });

            modelBuilder.Entity("REC4.Domain.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEmissaoRG")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeMae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoEmissorRG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UFRG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj")
                        .IsUnique()
                        .HasDatabaseName("IX_Pessoas_CpfCnpj_Ativas")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.PessoaPerfil", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.HasKey("PessoaId", "PerfilId");

                    b.HasIndex("PerfilId");

                    b.ToTable("PessoaPerfis", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.ContaBancaria", b =>
                {
                    b.HasOne("REC4.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("ContasBancarias")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("REC4.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("REC4.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("REC4.Domain.Entities.PessoaPerfil", b =>
                {
                    b.HasOne("REC4.Domain.Entities.Perfil", "Perfil")
                        .WithMany("PessoaPerfis")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REC4.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("PessoaPerfis")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("REC4.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("PessoaPerfis");
                });

            modelBuilder.Entity("REC4.Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("ContasBancarias");

                    b.Navigation("Enderecos");

                    b.Navigation("PessoaPerfis");
                });
#pragma warning restore 612, 618
        }
    }
}
