// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REC4.Infrastructure.Data;

#nullable disable

namespace REC4.Infrastructure.Data.Migrations
{
    [DbContext(typeof(Rec4DbContext))]
    partial class Rec4DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("REC4.Domain.Entities.ContaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DigitoConta")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContasBancarias_PessoaId_Principal")
                        .HasFilter("[IsPrincipal] = 1");

                    b.ToTable("ContasBancarias", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique()
                        .HasDatabaseName("IX_Enderecos_PessoaId_Principal")
                        .HasFilter("[IsPrincipal] = 1");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.Escritorio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Escritorios", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Grupos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Controladoria"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Financeiro"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Logística"
                        });
                });

            modelBuilder.Entity("REC4.Domain.Entities.GrupoPermissao", b =>
                {
                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.HasKey("GrupoId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("GrupoPermissoes", (string)null);

                    b.HasData(
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 1
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 2
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 3
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 4
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 5
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 6
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 7
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 8
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 9
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 10
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 11
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 12
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 13
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 14
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 15
                        },
                        new
                        {
                            GrupoId = 1,
                            PermissaoId = 16
                        },
                        new
                        {
                            GrupoId = 2,
                            PermissaoId = 7
                        },
                        new
                        {
                            GrupoId = 2,
                            PermissaoId = 8
                        },
                        new
                        {
                            GrupoId = 2,
                            PermissaoId = 9
                        },
                        new
                        {
                            GrupoId = 2,
                            PermissaoId = 10
                        },
                        new
                        {
                            GrupoId = 2,
                            PermissaoId = 11
                        },
                        new
                        {
                            GrupoId = 2,
                            PermissaoId = 1
                        },
                        new
                        {
                            GrupoId = 3,
                            PermissaoId = 12
                        },
                        new
                        {
                            GrupoId = 3,
                            PermissaoId = 13
                        },
                        new
                        {
                            GrupoId = 3,
                            PermissaoId = 1
                        });
                });

            modelBuilder.Entity("REC4.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Perfis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Cliente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Fornecedor"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Parceiro"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Colaborador"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Emitente"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Seguradora"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Proprietário"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Corretora"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Reguladora"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Responsável Financeiro"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Agenciador"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Motorista"
                        });
                });

            modelBuilder.Entity("REC4.Domain.Entities.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("Permissoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chave = "Pessoa.Visualizar",
                            Descricao = "Visualizar pessoas cadastradas"
                        },
                        new
                        {
                            Id = 2,
                            Chave = "Pessoa.Criar",
                            Descricao = "Cadastrar novas pessoas"
                        },
                        new
                        {
                            Id = 3,
                            Chave = "Pessoa.Editar",
                            Descricao = "Editar ou inativar pessoas cadastradas"
                        },
                        new
                        {
                            Id = 4,
                            Chave = "Usuario.Visualizar",
                            Descricao = "Visualizar usuários do sistema"
                        },
                        new
                        {
                            Id = 5,
                            Chave = "Usuario.Criar",
                            Descricao = "Cadastrar novos usuários"
                        },
                        new
                        {
                            Id = 6,
                            Chave = "Usuario.Editar",
                            Descricao = "Editar usuários existentes"
                        },
                        new
                        {
                            Id = 7,
                            Chave = "Financeiro.Visualizar",
                            Descricao = "Visualizar lançamentos financeiros"
                        },
                        new
                        {
                            Id = 8,
                            Chave = "Financeiro.Criar",
                            Descricao = "Criar lançamentos financeiros"
                        },
                        new
                        {
                            Id = 9,
                            Chave = "Financeiro.Editar",
                            Descricao = "Editar lançamentos financeiros"
                        },
                        new
                        {
                            Id = 10,
                            Chave = "Conciliacao.Visualizar",
                            Descricao = "Visualizar conciliação financeira"
                        },
                        new
                        {
                            Id = 11,
                            Chave = "Conciliacao.Editar",
                            Descricao = "Editar conciliação financeira"
                        },
                        new
                        {
                            Id = 12,
                            Chave = "Documento.Emitir",
                            Descricao = "Emitir documentos de transporte"
                        },
                        new
                        {
                            Id = 13,
                            Chave = "Documento.Visualizar",
                            Descricao = "Visualizar documentos de transporte"
                        },
                        new
                        {
                            Id = 14,
                            Chave = "Escritorio.Visualizar",
                            Descricao = "Visualizar escritórios cadastrados"
                        },
                        new
                        {
                            Id = 15,
                            Chave = "Escritorio.Criar",
                            Descricao = "Cadastrar novos escritórios"
                        },
                        new
                        {
                            Id = 16,
                            Chave = "Escritorio.Editar",
                            Descricao = "Editar escritórios existentes"
                        });
                });

            modelBuilder.Entity("REC4.Domain.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEmissaoRG")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeMae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoEmissorRG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UFRG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj")
                        .IsUnique()
                        .HasDatabaseName("IX_Pessoas_CpfCnpj_Ativas")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.PessoaPerfil", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.HasKey("PessoaId", "PerfilId");

                    b.HasIndex("PerfilId");

                    b.ToTable("PessoaPerfis", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LimiteDiasEdicaoFinanceiro")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TemPermissaoPersonalizada")
                        .HasColumnType("bit");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PessoaId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.UsuarioEmitente", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("UsuarioEmitentes", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.UsuarioEscritorio", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EscritorioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.HasKey("UsuarioId", "EscritorioId");

                    b.HasIndex("EscritorioId");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("IX_UsuarioEscritorios_UsuarioId_Principal")
                        .HasFilter("[IsPrincipal] = 1");

                    b.ToTable("UsuarioEscritorios", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.UsuarioPermissao", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("UsuarioPermissoes", (string)null);
                });

            modelBuilder.Entity("REC4.Domain.Entities.ContaBancaria", b =>
                {
                    b.HasOne("REC4.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("ContasBancarias")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("REC4.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("REC4.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("REC4.Domain.Entities.GrupoPermissao", b =>
                {
                    b.HasOne("REC4.Domain.Entities.Grupo", "Grupo")
                        .WithMany("GrupoPermissoes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REC4.Domain.Entities.Permissao", "Permissao")
                        .WithMany("GrupoPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("REC4.Domain.Entities.PessoaPerfil", b =>
                {
                    b.HasOne("REC4.Domain.Entities.Perfil", "Perfil")
                        .WithMany("PessoaPerfis")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REC4.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("PessoaPerfis")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("REC4.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("REC4.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Usuarios")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REC4.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grupo");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("REC4.Domain.Entities.UsuarioEmitente", b =>
                {
                    b.HasOne("REC4.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REC4.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioEmitentes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("REC4.Domain.Entities.UsuarioEscritorio", b =>
                {
                    b.HasOne("REC4.Domain.Entities.Escritorio", "Escritorio")
                        .WithMany("UsuarioEscritorios")
                        .HasForeignKey("EscritorioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REC4.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioEscritorios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escritorio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("REC4.Domain.Entities.UsuarioPermissao", b =>
                {
                    b.HasOne("REC4.Domain.Entities.Permissao", "Permissao")
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("REC4.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("REC4.Domain.Entities.Escritorio", b =>
                {
                    b.Navigation("UsuarioEscritorios");
                });

            modelBuilder.Entity("REC4.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("GrupoPermissoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("REC4.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("PessoaPerfis");
                });

            modelBuilder.Entity("REC4.Domain.Entities.Permissao", b =>
                {
                    b.Navigation("GrupoPermissoes");
                });

            modelBuilder.Entity("REC4.Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("ContasBancarias");

                    b.Navigation("Enderecos");

                    b.Navigation("PessoaPerfis");
                });

            modelBuilder.Entity("REC4.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioEmitentes");

                    b.Navigation("UsuarioEscritorios");

                    b.Navigation("UsuarioPermissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
